// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using databaseOtters.Model;

namespace databaseOtters.Migrations
{
    [DbContext(typeof(OtterDbContext))]
    [Migration("20200922131014_01Initial")]
    partial class _01Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("databaseOtters.Model.Location", b =>
                {
                    b.Property<int?>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Area")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("databaseOtters.Model.Otter", b =>
                {
                    b.Property<int?>("tattooID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MothertattooID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("tattooID");

                    b.HasIndex("MothertattooID");

                    b.HasIndex("placeName");

                    b.ToTable("Otters");
                });

            modelBuilder.Entity("databaseOtters.Model.Place", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.HasIndex("LocationID");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("databaseOtters.Model.Otter", b =>
                {
                    b.HasOne("databaseOtters.Model.Otter", "Mother")
                        .WithMany("children")
                        .HasForeignKey("MothertattooID");

                    b.HasOne("databaseOtters.Model.Place", "place")
                        .WithMany("Otters")
                        .HasForeignKey("placeName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("databaseOtters.Model.Place", b =>
                {
                    b.HasOne("databaseOtters.Model.Location", "location")
                        .WithMany("Places")
                        .HasForeignKey("LocationID");
                });
#pragma warning restore 612, 618
        }
    }
}
